name: Test stable release

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: ["main"]
env:
  HDF5_MPI: "ON"
  HDF5_DIR: "/usr/local/"
  DISPLAY: ":99.0"
  DEB_PYTHON_INSTALL_LAYOUT: deb_system

jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/cianwilson/fenicsx_subduction:v0.8.0
    env:
      PYVISTA_OFF_SCREEN: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check scripts
        working-directory: notebooks
        run: |
           jupyter nbconvert --NbConvertApp.export_format=script --ClearOutputPreprocessor.enabled=True Poisson1D.ipynb
           jupyter nbconvert --NbConvertApp.export_format=script --ClearOutputPreprocessor.enabled=True Poisson2D.ipynb
           jupyter nbconvert --NbConvertApp.export_format=script --ClearOutputPreprocessor.enabled=True Poisson2DSolutions.ipynb
           jupyter nbconvert --NbConvertApp.export_format=script --ClearOutputPreprocessor.enabled=True SubductionBenchmark.ipynb
           jupyter nbconvert --NbConvertApp.export_format=script --ClearOutputPreprocessor.enabled=True SubductionBenchmarkSolutions.ipynb
           git diff --name-only --exit-code

      - name: Test background
        working-directory: notebooks
        run: |
            python3 -c "from pyvista import start_xvfb; start_xvfb(0.1)"
            mpirun -n 2 python3 Poisson1D.py
            mpirun -n 2 python3 Poisson2DSolutions.py

